### ISSUE TITLE
Add a before route change method to short circuit the route change

### ISSUE THREAD

**Issue by matt-sneed** [Banno/web-component-router#51]
Currently there is no method to run a function and block route change before the router navigates to the next component. The use case that we are trying to solve is an unsaved changes check where a function could be called to check if there are unsaved changes and show a confirmation/save dialog to the user before the changes are lost. Currently the only way to do that is to use the "addRouteChangeStartCallback" method and then throw an uncaught exception.

**Comment by ChadKillingsworth** [comment]
This should be done in the traditional manner - intercepting 'click' events on anchor tags (or other methods) and calling `preventDefault()`. The browser doesn't let you block main navigation and a single-page router should not let you do that either.
